version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    assignees:
      - "k03mad"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - "k03mad"
