{
 "title": "ControlD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Activity Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTrigger\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Action (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Porn Domains (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerPornDomain\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nrd Domains (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"actionTriggerNrdDomain\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"protocol\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"rrType\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"deviceId\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source IP (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Geo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceGeoip\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Geo (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceGeoipDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source ISP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIsp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source ISP (device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"sourceIspDevice\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Answer Country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"answers\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Answer City",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "ctrld_devices_activity_log{activity=\"answersCity\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Statistics [week]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"all-by-verdict-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Filter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-filter-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Triggered By Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"service-triggered-by-service-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Location",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-location-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bypassed By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"bypassed-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-domain-week\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Statistics [month]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"all-by-verdict-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Filter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-filter-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Triggered By Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"service-triggered-by-service-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redirected By Location",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"redirected-by-location-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bypassed By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"bypassed-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Blocked By Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "ctrld_devices_reports{report=\"blocked-by-domain-month\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Inner Stat",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
   "targets": [
    { "expr": "ctrld_counters", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Last Request",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ctrld_devices_last_activity * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}