#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -n "${CTRLD_POST_MERGE_RESTART}" ]; then
    NO_FORMAT="\033[0m"
    F_BOLD="\033[1m"
    C_BLUE="\033[38;5;33m"

    echo "\n${F_BOLD}${C_BLUE}restarting exporter service...${NO_FORMAT}"
    systemctl restart ctrld-exporter.service
fi
