name: SSH

on:
  push:
    branches:
      - master

jobs:
  ssh:
    environment: vds
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/git/ctrld-prom-exporter
            git reset --hard
            git pull
            ~/.nvm/nvm-exec npm run setup
            systemctl restart ctrld-exporter.service
